/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosEventIdRouteImport } from './routes/eventos.$eventId'
import { Route as LigasIndexRouteImport } from './routes/ligas.index'
import { Route as LigasSlugRouteImport } from './routes/ligas.$slug'
import { Route as ApiAdminRecalculatePositionsRouteImport } from './routes/api/admin/recalculate-positions'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1RacesRouteImport } from './routes/api/v1/races'
import { Route as ApiPublicPagosWebhookRouteImport } from './routes/api/public/pagos.webhook'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api/v1/auth.login'
import { Route as ApiV1TimeRecordsBatchRouteImport } from './routes/api/v1/time-records.batch'
import { Route as ApiV1RacesRaceIdAthletesRouteImport } from './routes/api/v1/races.$raceId.athletes'
import { Route as ApiV1RacesRaceIdSplitsRouteImport } from './routes/api/v1/races.$raceId.splits'
import { Route as ApiV1RacesRaceIdWavesRouteImport } from './routes/api/v1/races.$raceId.waves'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosEventIdRoute = EventosEventIdRouteImport.update({
  id: '/eventos/$eventId',
  path: '/eventos/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasIndexRoute = LigasIndexRouteImport.update({
  id: '/ligas/',
  path: '/ligas/',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasSlugRoute = LigasSlugRouteImport.update({
  id: '/ligas/$slug',
  path: '/ligas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRecalculatePositionsRoute =
  ApiAdminRecalculatePositionsRouteImport.update({
    id: '/api/admin/recalculate-positions',
    path: '/api/admin/recalculate-positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RacesRoute = ApiV1RacesRouteImport.update({
  id: '/api/v1/races',
  path: '/api/v1/races',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPagosWebhookRoute = ApiPublicPagosWebhookRouteImport.update({
  id: '/api/public/pagos/webhook',
  path: '/api/public/pagos/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TimeRecordsBatchRoute = ApiV1TimeRecordsBatchRouteImport.update({
  id: '/api/v1/time-records/batch',
  path: '/api/v1/time-records/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RacesRaceIdAthletesRoute =
  ApiV1RacesRaceIdAthletesRouteImport.update({
    id: '/$raceId/athletes',
    path: '/$raceId/athletes',
    getParentRoute: () => ApiV1RacesRoute,
  } as any)
const ApiV1RacesRaceIdSplitsRoute = ApiV1RacesRaceIdSplitsRouteImport.update({
  id: '/$raceId/splits',
  path: '/$raceId/splits',
  getParentRoute: () => ApiV1RacesRoute,
} as any)
const ApiV1RacesRaceIdWavesRoute = ApiV1RacesRaceIdWavesRouteImport.update({
  id: '/$raceId/waves',
  path: '/$raceId/waves',
  getParentRoute: () => ApiV1RacesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/panel': typeof PanelRoute
  '/ranking': typeof RankingRoute
  '/eventos/$eventId': typeof EventosEventIdRoute
  '/ligas/$slug': typeof LigasSlugRoute
  '/eventos/': typeof EventosIndexRoute
  '/ligas/': typeof LigasIndexRoute
  '/api/admin/recalculate-positions': typeof ApiAdminRecalculatePositionsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/races': typeof ApiV1RacesRouteWithChildren
  '/api/public/pagos/webhook': typeof ApiPublicPagosWebhookRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/time-records/batch': typeof ApiV1TimeRecordsBatchRoute
  '/api/v1/races/$raceId/athletes': typeof ApiV1RacesRaceIdAthletesRoute
  '/api/v1/races/$raceId/splits': typeof ApiV1RacesRaceIdSplitsRoute
  '/api/v1/races/$raceId/waves': typeof ApiV1RacesRaceIdWavesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/panel': typeof PanelRoute
  '/ranking': typeof RankingRoute
  '/eventos/$eventId': typeof EventosEventIdRoute
  '/ligas/$slug': typeof LigasSlugRoute
  '/eventos': typeof EventosIndexRoute
  '/ligas': typeof LigasIndexRoute
  '/api/admin/recalculate-positions': typeof ApiAdminRecalculatePositionsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/races': typeof ApiV1RacesRouteWithChildren
  '/api/public/pagos/webhook': typeof ApiPublicPagosWebhookRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/time-records/batch': typeof ApiV1TimeRecordsBatchRoute
  '/api/v1/races/$raceId/athletes': typeof ApiV1RacesRaceIdAthletesRoute
  '/api/v1/races/$raceId/splits': typeof ApiV1RacesRaceIdSplitsRoute
  '/api/v1/races/$raceId/waves': typeof ApiV1RacesRaceIdWavesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/panel': typeof PanelRoute
  '/ranking': typeof RankingRoute
  '/eventos/$eventId': typeof EventosEventIdRoute
  '/ligas/$slug': typeof LigasSlugRoute
  '/eventos/': typeof EventosIndexRoute
  '/ligas/': typeof LigasIndexRoute
  '/api/admin/recalculate-positions': typeof ApiAdminRecalculatePositionsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/races': typeof ApiV1RacesRouteWithChildren
  '/api/public/pagos/webhook': typeof ApiPublicPagosWebhookRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/time-records/batch': typeof ApiV1TimeRecordsBatchRoute
  '/api/v1/races/$raceId/athletes': typeof ApiV1RacesRaceIdAthletesRoute
  '/api/v1/races/$raceId/splits': typeof ApiV1RacesRaceIdSplitsRoute
  '/api/v1/races/$raceId/waves': typeof ApiV1RacesRaceIdWavesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/panel'
    | '/ranking'
    | '/eventos/$eventId'
    | '/ligas/$slug'
    | '/eventos/'
    | '/ligas/'
    | '/api/admin/recalculate-positions'
    | '/api/v1/health'
    | '/api/v1/races'
    | '/api/public/pagos/webhook'
    | '/api/v1/auth/login'
    | '/api/v1/time-records/batch'
    | '/api/v1/races/$raceId/athletes'
    | '/api/v1/races/$raceId/splits'
    | '/api/v1/races/$raceId/waves'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/panel'
    | '/ranking'
    | '/eventos/$eventId'
    | '/ligas/$slug'
    | '/eventos'
    | '/ligas'
    | '/api/admin/recalculate-positions'
    | '/api/v1/health'
    | '/api/v1/races'
    | '/api/public/pagos/webhook'
    | '/api/v1/auth/login'
    | '/api/v1/time-records/batch'
    | '/api/v1/races/$raceId/athletes'
    | '/api/v1/races/$raceId/splits'
    | '/api/v1/races/$raceId/waves'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/panel'
    | '/ranking'
    | '/eventos/$eventId'
    | '/ligas/$slug'
    | '/eventos/'
    | '/ligas/'
    | '/api/admin/recalculate-positions'
    | '/api/v1/health'
    | '/api/v1/races'
    | '/api/public/pagos/webhook'
    | '/api/v1/auth/login'
    | '/api/v1/time-records/batch'
    | '/api/v1/races/$raceId/athletes'
    | '/api/v1/races/$raceId/splits'
    | '/api/v1/races/$raceId/waves'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PanelRoute: typeof PanelRoute
  RankingRoute: typeof RankingRoute
  EventosEventIdRoute: typeof EventosEventIdRoute
  LigasSlugRoute: typeof LigasSlugRoute
  EventosIndexRoute: typeof EventosIndexRoute
  LigasIndexRoute: typeof LigasIndexRoute
  ApiAdminRecalculatePositionsRoute: typeof ApiAdminRecalculatePositionsRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1RacesRoute: typeof ApiV1RacesRouteWithChildren
  ApiPublicPagosWebhookRoute: typeof ApiPublicPagosWebhookRoute
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1TimeRecordsBatchRoute: typeof ApiV1TimeRecordsBatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$eventId': {
      id: '/eventos/$eventId'
      path: '/eventos/$eventId'
      fullPath: '/eventos/$eventId'
      preLoaderRoute: typeof EventosEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas/': {
      id: '/ligas/'
      path: '/ligas'
      fullPath: '/ligas/'
      preLoaderRoute: typeof LigasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas/$slug': {
      id: '/ligas/$slug'
      path: '/ligas/$slug'
      fullPath: '/ligas/$slug'
      preLoaderRoute: typeof LigasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/recalculate-positions': {
      id: '/api/admin/recalculate-positions'
      path: '/api/admin/recalculate-positions'
      fullPath: '/api/admin/recalculate-positions'
      preLoaderRoute: typeof ApiAdminRecalculatePositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/races': {
      id: '/api/v1/races'
      path: '/api/v1/races'
      fullPath: '/api/v1/races'
      preLoaderRoute: typeof ApiV1RacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pagos/webhook': {
      id: '/api/public/pagos/webhook'
      path: '/api/public/pagos/webhook'
      fullPath: '/api/public/pagos/webhook'
      preLoaderRoute: typeof ApiPublicPagosWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/time-records/batch': {
      id: '/api/v1/time-records/batch'
      path: '/api/v1/time-records/batch'
      fullPath: '/api/v1/time-records/batch'
      preLoaderRoute: typeof ApiV1TimeRecordsBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/races/$raceId/athletes': {
      id: '/api/v1/races/$raceId/athletes'
      path: '/$raceId/athletes'
      fullPath: '/api/v1/races/$raceId/athletes'
      preLoaderRoute: typeof ApiV1RacesRaceIdAthletesRouteImport
      parentRoute: typeof ApiV1RacesRoute
    }
    '/api/v1/races/$raceId/splits': {
      id: '/api/v1/races/$raceId/splits'
      path: '/$raceId/splits'
      fullPath: '/api/v1/races/$raceId/splits'
      preLoaderRoute: typeof ApiV1RacesRaceIdSplitsRouteImport
      parentRoute: typeof ApiV1RacesRoute
    }
    '/api/v1/races/$raceId/waves': {
      id: '/api/v1/races/$raceId/waves'
      path: '/$raceId/waves'
      fullPath: '/api/v1/races/$raceId/waves'
      preLoaderRoute: typeof ApiV1RacesRaceIdWavesRouteImport
      parentRoute: typeof ApiV1RacesRoute
    }
  }
}

interface ApiV1RacesRouteChildren {
  ApiV1RacesRaceIdAthletesRoute: typeof ApiV1RacesRaceIdAthletesRoute
  ApiV1RacesRaceIdSplitsRoute: typeof ApiV1RacesRaceIdSplitsRoute
  ApiV1RacesRaceIdWavesRoute: typeof ApiV1RacesRaceIdWavesRoute
}

const ApiV1RacesRouteChildren: ApiV1RacesRouteChildren = {
  ApiV1RacesRaceIdAthletesRoute: ApiV1RacesRaceIdAthletesRoute,
  ApiV1RacesRaceIdSplitsRoute: ApiV1RacesRaceIdSplitsRoute,
  ApiV1RacesRaceIdWavesRoute: ApiV1RacesRaceIdWavesRoute,
}

const ApiV1RacesRouteWithChildren = ApiV1RacesRoute._addFileChildren(
  ApiV1RacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PanelRoute: PanelRoute,
  RankingRoute: RankingRoute,
  EventosEventIdRoute: EventosEventIdRoute,
  LigasSlugRoute: LigasSlugRoute,
  EventosIndexRoute: EventosIndexRoute,
  LigasIndexRoute: LigasIndexRoute,
  ApiAdminRecalculatePositionsRoute: ApiAdminRecalculatePositionsRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1RacesRoute: ApiV1RacesRouteWithChildren,
  ApiPublicPagosWebhookRoute: ApiPublicPagosWebhookRoute,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1TimeRecordsBatchRoute: ApiV1TimeRecordsBatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
